package registration;

import java.util.Date;

/**
 *
 * @author Samir
 */
public class Student {

    private String firstName;
    private String lastName;
    private String address;
    private String phoneNumber;
    private String email;
    private double paidFees;
    private Date date;
    private CourseType course;
    private StudentType type;
    private long id; // This field is autogenerated upon object creation

    /**
     * Student constructor
     * 
     * @param firstName
     * @param lastName
     * @param address
     * @param telephone
     * @param email
     * @param course
     * @param paidFees
     * @param date
     * @param type
     * @param id 
     */
    public Student(String firstName, String lastName, String address, String telephone, String email, CourseType course, double paidFees, Date date, StudentType type, long id) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.phoneNumber = telephone;
        this.email = email;
        this.course = course;
        this.date = date;
        this.paidFees = paidFees;
        this.type = type;
        this.id = id;
    }

    /**
     * @return the firstName
     */
    public String getFirstName() {
        return firstName;
    }

    public StudentType getStudentType() {
        return type;
    }

    /**
     * @return the lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @return the address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @return the phoneNumber
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @return the fees
     */
    public double getFees() {
        return paidFees;
    }

    /**
     * @return the date
     */
    public Date getDate() {
        return date;
    }

    /**
     * @return the course
     */
    public CourseType getCourse() {
        return course;
    }

    /**
     * @return the id
     */
    public long getId() {
        return id;
    }

    /**
     * @param firstName the firstName to set
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @param lastName the lastName to set
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @param phoneNumber the phoneNumber to set
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @param fees the fees to set
     */
    public void setFees(double fees) {
        this.paidFees = fees;
    }

    /**
     * @param date the date to set
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * @param course the course to set
     */
    public void setCourse(CourseType course) {
        this.course = course;
    }

}
